### ISSUE TITLE
Rehabman stealing PJALM's configs

### ISSUE THREAD

**Issue by macmeister1967** [khronokernel/What-s-new-in-macOS-Catalina#2]
> Rehabman stealing PJALM's configs

Can you provide some reliable proof (or even another mention) of this happening?

This is the only mention I can find on the internet via Google/Bing ???

**Comment by khronokernel** [comment]
PJALM sent take downs to Rehabman, you can speak to PJALM himself or people around him for more info on what happened. I won't speak on their behalf. Dwarfy/MuffinCrumbs is also another person you can speak to about this matter as they're the one who originally brought this up.
